### PR TITLE
Semphris, you goober.

### PR DESCRIPTION
**Pull request by tylerandari13**
With the new tileset PR comes new funnies that we gotta convert. This PR will convert the tiles and optimize the tile file.

This comes with everything needed to convert all levels. They will beconverted just before merging to avoid conflicts.

### CODE REVIEW

**Comment by Frostwithasideofsalt** [comment]
huh

**Comment by Frostwithasideofsalt** [comment]
this has merge conflicts lol

**Comment by tylerandari13** [comment]
lmao

**Comment by tylerandari13** [comment]
Is there a way to wipe a PR clean and start over?

**Comment by Frostwithasideofsalt** [comment]
i honestly have no clue

**Comment by tylerandari13** [comment]
Tbh we might not even need to do anything with this yet, Semphris and his PR are dead and we can probably make a new one for when Vankata makes his ~~probably superior~~ Tiles PR.

**Comment by Frostwithasideofsalt** [comment]
:gatom:

**Comment by tylerandari13** [comment]
closing this and opening a new PR to just start over

**Pull request closed without merging**
